services:
  - type: web
    name: investments-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
